require 'share_progress'
require 'share_progress/twitter_variant'
require 'share_progress/facebook_variant'
require 'share_progress/email_variant'
require 'share_progress/variant_parser'

module ShareProgress
  describe VariantParser do
    let(:facebook_hash) { {"id" => 62899,"facebook_title" => nil,"facebook_description" => nil,"facebook_thumbnail" => nil} }
    let(:twitter_hash) { {"id" => 62897,"twitter_message" => nil } }
    let(:email_hash) { {"id" => 62898,"email_subject" => nil,"email_body" => nil} }

    describe 'with valid hash' do

      [FacebookVariant, TwitterVariant, EmailVariant].each do |variant_class|         
        describe "parsing #{variant_class}" do

          variant_class.fields.each do |field|        
            describe "with only key #{field}" do

              [[:to_s, 'symbol'], [:to_sym, 'string']].each do |key_type, key_type_name|

                let(:variant_hash) { {field.send(key_type) => 'ni importa'} }

                it "as #{key_type_name} type correctly parses class" do
                  expect(VariantParser.parse(variant_hash)).to eq variant_class
                end

              end
            end
          end
        end
      end

      describe 'auto-generated by API' do

        it 'is parsed as FacebookVariant' do
          expect(VariantParser.parse(facebook_hash)).to eq FacebookVariant
        end

        it 'is parsed as TwitterVariant' do
          expect(VariantParser.parse(twitter_hash)).to eq TwitterVariant
        end

        it 'is parsed as EmailVariant' do
          expect(VariantParser.parse(email_hash)).to eq EmailVariant
        end
      end
    end

    describe 'with invalid hash' do

      after :each do
        expect{ VariantParser.parse(@variant_hash) }.to raise_error ShareProgress::CouldNotParseVariant
      end

      it 'that has no keys' do
        @variant_hash = {}
      end

      it 'that has only unknown keys' do
        @variant_hash = { made_up_key: 1, 'other_key' => 'derp'}
      end

      it 'that has only id' do
        @variant_hash = { id: 12345 }
      end

      it 'has keys from two different types' do
        @variant_hash = facebook_hash.merge(email_hash)
      end
    end

  end
end
